name: Labeler

on:
  push:
    branches:
      - main
      - master
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"
  pull_request:
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          skip-delete: True
          yaml-file: .github/labels.yml
          exclude: |
            help*
            *issue
